- name: Sass Build
  uses: gha-utilities/sass-build@v0.2.5

on:
  push:
    branches:
      - master


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 10
            submodules: true
            
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/transparent.scss
          destination: _bbd/css/main.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/buttons.scss
          destination: _bbd/css/main.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/settings.scss
          destination: _bbd/css/main.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/profile_modal.scss
          destination: _bbd/css/main.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: pr-pages
            fetch-depth: 1

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add _bbd/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
