on:
  push:
    branches:
      - master


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 10
            submodules: true
            
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/transparent.scss
          destination: _bbd/css/transparent.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/buttons.scss
          destination: _bbd/css/buttons.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/settings.scss
          destination: _bbd/css/settings.css
          
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.0
        with:
          source: basics/profile_modal.scss
          destination: _bbd/css/profile_modal.css

      - name: Add and Commit changes to master branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add _bbd/css/*
          git diff-index --quiet HEAD || git commit -m '🛠️ Built CSS From SASS'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_ACC_TOKEN }}
          branch: master
